---

- hosts: all
  become: true
  tasks:

  - name: install the apache and php support packages
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"
