---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always  
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true 
  tasks:

  - name: install the apache and php support packages
    tags: apache,apache2,ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install the PostgreSQL package on our server
    tags: postgresql,ubuntu,db
    apt:
      name: postgresql
      state: latest
      update_cache: yes    


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba,ubuntu
    package: 
      name: samba
      state: latest
