---

- hosts: all
  become: true
  tasks:

  - name: update cache
    tags: always  
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles: 
    - base
    
- hosts: web_servers
  become: true 
  roles:
    - web_servers
  
- hosts: workstations
  become: true
  roles: 
    - workstations 
  
- hosts: db_servers
  become: true
  roles: 
    - db_servers

- hosts: file_servers
  become: true
  roles: 
    - file_servers 

