  - name: install the apache and php support packages
    tags: apache,apache2,ubuntu
    package:
      name:   
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
      
  - name: start the apache2 service on our ubuntu service so we can view the webpage
    tags: ubuntu,apache2,apache
    service:
      name: apache2 
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: copy website file to server
    tags: apache,apache2,ubuntu
    copy:   
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root  
      mode: 0644

